[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "linux-multimodal-assistant"
version = "0.1.0"
description = "Linux Multimodal Assistant"
readme = "README.md"
requires-python = ">=3.8"
